name: snap_n_eat
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.1
  flutter_custom_tabs: "^0.6.0"
  oauth2_client: ^1.3.0
  flutter_svg: ^0.17.4
  fluid_bottom_nav_bar: ^1.0.1
  percent_indicator: "^2.1.5"
  intl: ^0.16.1
  shared_preferences: ^0.5.8 
  firebase_analytics: ^5.0.16
  cloud_firestore: ^0.13.4+2
  fl_chart: ^0.10.1
  provider: ^4.0.1
  fluttertoast: ^7.0.1
  share: ^0.6.4+3
    
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/account_circle.svg
    - assets/icons/dashboard.svg
    - assets/icons/leaderboard.svg
    - assets/icons/foot.svg
    - assets/icons/distance.svg
    - assets/icons/profile.svg
    - assets/icons/blue-dashboard.svg
    - assets/icons/calorie.svg
    - assets/icons/analytics.svg
    - assets/icons/stairs.svg
    - assets/icons/moon.svg
    - assets/icons/list-box.svg
    - assets/icons/heartbeat.svg
    - assets/icons/heartline.svg
    - assets/icons/bmi.svg
    - assets/icons/height.svg
    - assets/icons/icon_email.svg
    - assets/icons/line.svg
    - assets/icons/radial_gradient.svg
    - assets/icons/weight-scale.svg
    - assets/icons/logo.png
    - assets/icons/friend.svg
    - assets/icons/friendNav.svg
    - assets/icons/challenge.svg
    - assets/icons/addFriend.svg
    - assets/icons/check.svg
    - assets/icons/clear.svg
    - assets/icons/crown.svg
    - assets/icons/star.svg
    - assets/icons/vs.svg







  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
